### ISSUE TITLE
dotnet-cli module regression - incorrect command string to dotnet 

### ISSUE THREAD

**Issue by brandongregoryscott** [AndcultureCode/AndcultureCode.Cli#102]
Probably a side effect of the way the command string is being built out w/ the recent refactor (#98)
'Full command' should be `dotnet Cli.dll test db migrate`, not `dotnet Cli.dll test,db,migrate`

```
[and-cli] Full command:dotnet Cli.dll test,db,migrate
Specify --help for a list of available options and commands.
Unhandled exception. McMaster.Extensions.CommandLineUtils.UnrecognizedCommandParsingException: Unrecognized command or argument 'test,db,migrate'
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.HandleUnexpectedArg(String argTypeName, String argValue)
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessCommandOrArgument()
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessNext()
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.Process()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Parse(String[] args)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Nfpa.CodesApi.Presentation.Cli.Program.Main(String[] args) in C:\Users\bscot\nfpa\dotnet\api\Presentation\Cli\Program.cs:line 125
[and-cli] [ERROR] Command failed, see output for details.
```

The array created on line 28 of `modules/dotnet-cli.js` probably needs to be expanded using `...` syntax:
```JS
    cmd(cliArgs = "") {
        const pathName = path.basename(dotnetPath.cliPath() || "");
        return commandStringFactory.build(
            "dotnet",
            pathName,
            ...cliArgs.split(" ")
        );
    },
```

**Comment by brandongregoryscott** [comment]
Published with [v1.1.3](https://github.com/AndcultureCode/AndcultureCode.Cli/releases/tag/v1.1.3)
