### ISSUE TITLE
Assignment to constant variable error in dotnet-test module

### ISSUE THREAD

**Issue by brandongregoryscott** [AndcultureCode/AndcultureCode.Cli#104]
Not sure how this one slipped by in my recent refactorings 😓 

```
[and-cli] Full command:dotnet Cli.dll test db migrate
[Dotnet.Cli] Migrating test database 'CodesApi-Test'...
[Dotnet.Cli]  - Successfully migrated test database.
[and-cli] Found 9 test projects in the dotnet/api solution...
(node:99084) UnhandledPromiseRejectionWarning: TypeError: Assignment to constant variable.
    at _buildCommandString (C:\Users\bscot\proj\node_modules\and-cli\modules\dotnet-test.js:92:10)
    at Object.runProject (C:\Users\bscot\proj\node_modules\and-cli\modules\dotnet-test.js:177:31)
    at testProjects.map (C:\Users\bscot\proj\node_modules\and-cli\modules\dotnet-test.js:236:18)
    at Array.map (<anonymous>)
    at Object.runSolutionByProject (C:\Users\bscot\proj\node_modules\and-cli\modules\dotnet-test.js:235:38)
    at require.run (C:\Users\bscot\proj\node_modules\and-cli\and-cli-dotnet-test.js:44:20)
    at Object.module.exports.run (C:\Users\bscot\proj\node_modules\and-cli\command-runner.js:10:11)
    at Object.<anonymous> (C:\Users\bscot\proj\node_modules\and-cli\and-cli-dotnet-test.js:2:29)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
(node:99084) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:99084) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The `args` variable on line 73 should actually be declared with `let`, not `const`.

**Comment by brandongregoryscott** [comment]
Fixed in [v1.2.0](https://github.com/AndcultureCode/AndcultureCode.Cli/releases/tag/v1.2.0)
