### ISSUE TITLE
Fix dependency conflict between awscli and awsebcli

### ISSUE THREAD

**Issue by wintondeshong** [AndcultureCode/AndcultureCode.Cli#33]
**Problem**
[and-cli] Deploying to AWS beanstalk. Check AWS console for realtime output. This could take a few minutes...
Traceback (most recent call last):
  File "C:\Python27\Scripts\eb-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 3017, in <module>
    @_call_aside
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 3030, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 661, in _build_master
    return cls._build_from_requirements(__requires__)
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 674, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 853, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'botocore<1.13,>=1.12.29' distribution was not found and is required by awsebcli
[and-cli] [ERROR]  - Failed to deploy to AWS beanstalk

**Solution**
Turns out we must specify explicit awscli and awsebcli versions to ensure their subdependencies align.

**Comment by wintondeshong** [comment]
Already have a fix in the works
